window.CLIENT_LIST = [
{num_contrato:"RGD001035",	nome:"ADMIntermare"},
{num_contrato:"RGD001217",	nome:"AMAGGI AS C/O PORTS DIRECT"},
{num_contrato:"RGD001136",	nome:"BBC INV"},
{num_contrato:"RGD001137",	nome:"BBC INV"},
{num_contrato:"RGD001022",	nome:"CANPOTEX SHIPPING SERVICES LIMITED - C/O PORTS-DIRECT RZE"},
{num_contrato:"RGD001138",	nome:"CHEMBULK TRADING II LLC"},
{num_contrato:"RGD001262",	nome:"COSCO - STS"},
{num_contrato:"RGD000968",	nome:"DAMICO GROUP C/O SSY"},
{num_contrato:"RGD001103",	nome:"EVERGREEN MARINE CORP A/C AG VAP. GRIEG"},
{num_contrato:"RGD001049",	nome:"GLENCORE GRAIN B.V."},
{num_contrato:"RGD001186",	nome:"GRANEL - RGD"},
{num_contrato:"RGD001187",	nome:"GRANEL - RGD"},
{num_contrato:"RGD001188",	nome:"GRANEL - RGD"},
{num_contrato:"RGD001189",	nome:"GRANEL - RGD"},
{num_contrato:"RGD001251",	nome:"GRANEL - STS"},
{num_contrato:"RGD001220",	nome:"HAFNIA MANAGEMENT AS C/O PORTS DIRECT"},
{num_contrato:"RGD000801",	nome:"HAMBURG SUD - SP"},
{num_contrato:"RGD001257",	nome:"INTEGRITY BULK APS C/O PORTS DIRECT"},
{num_contrato:"RGD001153",	nome:"INTERMARINE INC."},
{num_contrato:"RGD001116",	nome:"ITALIA MARITTIMA SPA. A/C AG. VAP GRIEG "},
{num_contrato:"RGD000898",	nome:"MAERSK TANKERS"},
{num_contrato:"RGD001146",	nome:"NIDERA S.P.A."},
{num_contrato:"RGD001160",	nome:"NIDERA S.P.A."},
{num_contrato:"RGD001238",	nome:"NIDERA S.P.A."},
{num_contrato:"RGD000984",	nome:"PAN OCEAN CO., LTD"},
{num_contrato:"RGD001144",	nome:"PANCOAST TRADING"},
{num_contrato:"RGD001239",	nome:"PETROLEO BRASILEIRO S/A. PETROBRAS"},
{num_contrato:"RGD000982",	nome:"RAFFLES SHIPPING INTERNATIONAL PTE LTD. (BULKERS)"},
{num_contrato:"RGD000973",	nome:"REBRAS S/A"},
{num_contrato:"RGD001093",	nome:"ROCHAMAR AGENCIA MARITIMA S/A"},
{num_contrato:"RGD001019",	nome:"SAGA WELCO AS"},
{num_contrato:"RGD000974",	nome:"SAVEIROS - RGD"},
{num_contrato:"RGD001104",	nome:"SEM CONTRATO"},
{num_contrato:"RGD001234",	nome:"STENA WECO"},
{num_contrato:"RGD001265",	nome:"STOLT TANKERS B.V - STS"},
{num_contrato:"RGD001094",	nome:"THE RICE COMPANY"},
{num_contrato:"RGD001149",	nome:"THE RICE COMPANY"},
{num_contrato:"RGD001215",	nome:"THORCO SHIPPING A/S C/O PORTS DIRECT"},
{num_contrato:"RGD001119",	nome:"T.K.B. SHIPPING A/S C/O PORTS DIRECT"},
{num_contrato:"RGD001235",	nome:"TRANSGRAIN SHIPPING B.V. "},
{num_contrato:"RGD001264",	nome:"TRANSGRAIN SHIPPING PTE."},
{num_contrato:"RGD000860",	nome:"WALLENIUS - STS"},
{num_contrato:"RGD001269",	nome:"WORTHINGTON"},
{num_contrato:"RGD001194",	nome:"KOCH SHIPPING INC C/O PORTS DIRECT"},
{num_contrato:"VIT000670",	nome:"ADMIntermare"},
{num_contrato:"VIT000552",	nome:"ALIANÇA NAVEGAÇÃO E LOGÍSTICA LTDA."},
{num_contrato:"VIT000760",	nome:"BBC"},
{num_contrato:"VIT000761",	nome:"BBC"},
{num_contrato:"VIT000744",	nome:"CAMORIM"},
{num_contrato:"VIT000698",	nome:"CANPOTEX SHIPPING SERVICES LIMITED - C/O PORTS-DIRECT RZE"},
{num_contrato:"VIT000675",	nome:"D´AMICO DRY LIMITED AC SSY"},
{num_contrato:"VIT000696",	nome:"EDF TRADING MARKETS LIMITED"},
{num_contrato:"VIT000783",	nome:"ELCANO"},
{num_contrato:"VIT000740",	nome:"GEARBULK MANAGEMENT LIMITED"},
{num_contrato:"VIT000712",	nome:"GLENCORE GRAIN B.V."},
{num_contrato:"VIT000714",	nome:"GLOBAL CHARTERING LTD., MAURITIUS "},
{num_contrato:"VIT000793",	nome:"GOLDEN OCEAN MANAGEMENT AS"},
{num_contrato:"VIT000587",	nome:"HAMBURG SUD - SP"},
{num_contrato:"VIT000771",	nome:"INTERMARINE INC."},
{num_contrato:"VIT000685",	nome:"PAN OCEAN"},
{num_contrato:"VIT000767",	nome:"PANCOAST TRADING"},
{num_contrato:"VIT000663",	nome:"RAFFLES SHIPPING INTERNATIONAL PTE LTD. (BULKERS)"},
{num_contrato:"VIT000707",	nome:"RWE SUPLLY & TRADING GMBH C/O PORTS-DIRECT"},
{num_contrato:"VIT000745",	nome:"SAAM SMIT TOWAGE BRASIL"},
{num_contrato:"VIT000555",	nome:"SAGA WELCO AS"},
{num_contrato:"VIT000743",	nome:"SAVEIROS - VIT"},
{num_contrato:"VIT000739",	nome:"SEM CONTRATO"},
{num_contrato:"VIT000677",	nome:"SMT SHIP MANAGEMENT AND TRANSPORT LTD"},
{num_contrato:"VIT000697",	nome:"THORCO SHIPPING A/S C/O PORTS DIRECT"},
{num_contrato:"VIT000791",	nome:"TRANSGRAIN"},
{num_contrato:"VIT000018",	nome:"VALE DO RIO DOCE - VIT"},
{num_contrato:"VIT000603",	nome:"WALLENIUS WILHELMSEN SERV. DE LOGISTICA DO BRASIL LTDA"},
{num_contrato:"VIT000646",	nome:"WILHELMSEN SHIPS SERVICE DO BRASIL LTDA"},
{num_contrato:"VIT000613",	nome:"WORTHINGTON"},
{num_contrato:"MAC000527",	nome:"EMPRESA DE NAVEGACAO ELCANO S/A"},
{num_contrato:"MAC000420",	nome:"HAMBURG SUD DO BRASIL LTDA."},
{num_contrato:"MAC000506",	nome:"JUMBO SHIPPING-KAHN S. C/O PORTS DIRECT"},
{num_contrato:"MAC000516",	nome:"LOCAR GUINDASTES E TRANSPORTES INTERMODAIS S/A"},
{num_contrato:"MAC000529",	nome:"MAESTRO SHIPPING BV, The Netherlands"},
{num_contrato:"MAC000439",	nome:"NAVIG8 CHEMICALS POOL INC C/O NAVIG8 CHEMICALS ASIA PTE LTD"},
{num_contrato:"MAC000531",	nome:"POLA MARIS NV"},
{num_contrato:"MAC000517",	nome:"PROBULK SHIPPING & TRADING S.A"},
{num_contrato:"MAC000508",	nome:"SUISSE - ATLANTIQUE S.A."},
{num_contrato:"MAC000504",	nome:"T. K. B. SHIPPINS AS C/O PORTS DIRECT"},
{num_contrato:"MAC000353",	nome:"WESTERN BULK AS"},
{num_contrato:"SDR001157",	nome:"AGÊNCIA MARÍTIMA BRANDÃO FILHOS LTDA"},
{num_contrato:"SDR001085",	nome:"AGÊNCIA MARÍTIMA GRANEL LTDA."},
{num_contrato:"SDR001079",	nome:"BAHIA TANKERS AGENCIA MARITIMA LTDA"},
{num_contrato:"SDR001170",	nome:"CONE SUL AGENCIA DE NAVEGAÇÃO LTDA "},
{num_contrato:"SDR001078",	nome:"GAC LOGISTICA BRASIL LTDA"},
{num_contrato:"SDR001172",	nome:"HANSA TANKERS C/ O SSY"},
{num_contrato:"SDR001179",	nome:"ISS MARINE SERVICES LTDA"},
{num_contrato:"SDR001150",	nome:"MANSEL LTD C/O VITOL SERVICES LTD"},
{num_contrato:"SDR001146",	nome:"NORTH STAR SERVIÇOS MARÍTIMOS LTDA"},
{num_contrato:"SDR001140",	nome:"OCEANUS AGENCIA MARITIMA S.A - SDR"},
{num_contrato:"SDR001148",	nome:"ORION RODOS MARITIMA E PORTUARIA LTDA - VIT"},
{num_contrato:"SDR000962",	nome:"PETROBRAS"},
{num_contrato:"SDR000963",	nome:"PETROBRAS"},
{num_contrato:"SDR000979",	nome:"PETROBRAS"},
{num_contrato:"SDR001133",	nome:"ROCHAMAR AGENCIA MARITIMA S.A. SDR"},
{num_contrato:"SDR001151",	nome:"ST SHIPPING & TRANSPORT PTE LTD"},
{num_contrato:"SDR001091",	nome:"STAR SHIP AG¿CIA MAR¿IMA LTDA"},
{num_contrato:"SDR001175",	nome:"STOLT TANKERS B.V - STS"},
{num_contrato:"SDR000959",	nome:"WILLIAMS SERVIÇOS MARITIMOS LTDA - SDR"},
{num_contrato:"SDR000745",	nome:"AGÊNCIA MARÍTIMA GRANEL LTDA."},
{num_contrato:"SDR001152",	nome:"ALIANÇA NAVEGAÇÃO E LOGÍSTICA LTDA (SDR)"},
{num_contrato:"SDR001169",	nome:"BAHIA SHIP AGENCIA MARITIMA LTDA"},
{num_contrato:"SDR001126",	nome:"BBC CHARTERING CARRIERS GMBH & CO. KG"},
{num_contrato:"SDR001068",	nome:"CANPOTEX SHIPPING SERVICES LIMITED - C/O PORTS-DIRECT RZE"},
{num_contrato:"SDR001063",	nome:"D'AMICO GROUP C/O SSY"},
{num_contrato:"SDR001177",	nome:"ELACIR VIANNA DE SOUZA - ME (ICAROS AGENCIA MARITIMA)"},
{num_contrato:"SDR001171",	nome:"EMPRESA DE NAVEGACAO ELCANO S/A"},
{num_contrato:"SDR000747",	nome:"FLUMAR TRANSPORTES DE QUIMICOS E GASES LTDA -SDR"},
{num_contrato:"SDR001114",	nome:"GEARBULK MANAGEMENT LIMITED ¿ ROHQ"},
{num_contrato:"SDR001163",	nome:"HAFNIA MANAGEMENT AS C/O PORTS DIRECT"},
{num_contrato:"SDR000885",	nome:"HAMBURG SUD DO BRASIL LTDA."},
{num_contrato:"SDR001131",	nome:"HANSA TANKERS C/ O SSY"},
{num_contrato:"SDR001031",	nome:"INTERMARINE INC."},
{num_contrato:"SDR001139",	nome:"KOCH SHIPPING INC C/O PORTS DIRECT"},
{num_contrato:"SDR001176",	nome:"MAESTRO SHIPPING BV, The Netherlands"},
{num_contrato:"SDR000980",	nome:"NAVIG8 CHEMICALS C/O NAVIG8 PTE LTD"},
{num_contrato:"SDR001173",	nome:"PETROBRAS"},
{num_contrato:"SDR001167",	nome:"POLA MARIS NV"},
{num_contrato:"SDR001028",	nome:"SAGA WELCO AS"},
{num_contrato:"SDR001047",	nome:"SAVEIROS"},
{num_contrato:"SDR001045",	nome:"SMIT REBRAS"},
{num_contrato:"SDR001090",	nome:"STENA WECO A/S C/O PORTS DIRECT"},
{num_contrato:"SDR001019",	nome:"STOLT TANKERS B.V - STS"},
{num_contrato:"SDR001168",	nome:"TRANSGRAIN SHIPPING B.V."},
{num_contrato:"SDR001142",	nome:"TUGBRASIL"},
{num_contrato:"SDR001147",	nome:"UNITED BULK CARRIERS INTERNATIONAL"},
{num_contrato:"SDR000776",	nome:"WESTERN BULK AS"},
{num_contrato:"SDR001127",	nome:"WILHELMSEN SHIPS SERVICE DO BRASIL LTDA"},
{num_contrato:"STR000593",	nome:"ADMIntermare"},
{num_contrato:"STR000653",	nome:"AGENCIA DE VAPORES GRIEG S/A - STS"},
{num_contrato:"STR000602",	nome:"AGRI PORT SERVICES BRASIL LTDA"},
{num_contrato:"STR000443",	nome:"AGÊNCIA MARÍTIMA GRANEL LTDA. - STS"},
{num_contrato:"STR000507",	nome:"ALIANÇA NAVEGAÇÃO E LOGÍSTICA LTDA."},
{num_contrato:"STR000620",	nome:"AMAGGI SA C/O PORTS DIRECT"},
{num_contrato:"STR000465",	nome:"BALTNAV A/S"},
{num_contrato:"STR000669",	nome:"BBC CHARTERING CARRIERS GMBH & CO. KG"},
{num_contrato:"STR000713",	nome:"BPA AGENCIAMENTOS MARITIMO LTDA - STS - STS"},
{num_contrato:"STR000623",	nome:"CANPOTEX SHIPPING SERVICES LIMITED"},
{num_contrato:"STR000670",	nome:"CHEMBULK OCEAN TRANSPORT LLC"},
{num_contrato:"STR000748",	nome:"COSCO BRASIL S/A - STS"},
{num_contrato:"STR000749",	nome:"D¿AMICO DRY LIMITED AC SSY"},
{num_contrato:"STR000723",	nome:"EMPRESA DE NAVEGACAO ELCANO S/A"},
{num_contrato:"STR000446",	nome:"FLUMAR TRANSP. DE QUÍMICOS E GASES LTDA - STS"},
{num_contrato:"STR000654",	nome:"GEARBULK MANAGEMENT LIMITED ¿ ROHQ"},
{num_contrato:"STR000629",	nome:"GLENCORE GRAIN B.V."},
{num_contrato:"STR000719",	nome:"GULF ENERGY MARITIME (GEM) PJSC C/O PORTS DIRECT "},
{num_contrato:"STR000633",	nome:"HAFNIA MANAGEMENT AS C/O PORTS DIRECT"},
{num_contrato:"STR000536",	nome:"HAMBURG SUD DO BRASIL LTDA."},
{num_contrato:"STR000635",	nome:"HANSA TANKERS C/ O SSY"},
{num_contrato:"STR000636",	nome:"HOLBUD SHIP MANAGEMENT LIMITED"},
{num_contrato:"STR000686",	nome:"INTERMARINE INC."},
{num_contrato:"STR000676",	nome:"ISS MARINE SERVICES LTDA - STS"},
{num_contrato:"STR000726",	nome:"JALDHI OVERSEAS PTE LTD."},
{num_contrato:"STR000712",	nome:"JUMBO SHIPPING-KAHN S. C/O PORTS DIRECT"},
{num_contrato:"STR000665",	nome:"KOCH SHIPPING INC C/O PORTS DIRECT"},
{num_contrato:"STR000585",	nome:"MAERSK TANKERS A/S"},
{num_contrato:"STR000734",	nome:"MANSEL LTD C/O VITOL SERVICES LTD"},
{num_contrato:"STR000565",	nome:"NAVIG8 CHEMICALS POOL INC C/O NAVIG8 CHEMICALS ASIA PTE LTD"},
{num_contrato:"STR000696",	nome:"NIDERA S.P.A."},
{num_contrato:"STR000683",	nome:"OCEAN WORLD SHIPPING"},
{num_contrato:"STR000601",	nome:"OCEANUS AGENCIA MARÍTIMA S/A - STS"},
{num_contrato:"STR000627",	nome:"OCEANUS AGENCIA MARÍTIMA S/A - STS"},
{num_contrato:"STR000641",	nome:"OLDENDORF CARRIERS GMBH & CO."},
{num_contrato:"STR000745",	nome:"ORIZON MARITIME AGENCY INC"},
{num_contrato:"STR000650",	nome:"PAN OCEAN CO., LTD"},
{num_contrato:"STR000740",	nome:"PANCOAST TRADING S.A"},
{num_contrato:"STR000747",	nome:"PEGASUS AGENCIA MARITIMA LTDA - SDR"},
{num_contrato:"STR000742",	nome:"PETROBRAS"},
{num_contrato:"STR000510",	nome:"POLSTEAM SHIPPING COMPANY (NZ) LTD "},
{num_contrato:"STR000659",	nome:"PULLMANTUR CRUISES SHIP MANAGEMENT"},
{num_contrato:"STR000671",	nome:"RAFFLES SHIP CHARTERING PTE LTD."},
{num_contrato:"STR000643",	nome:"ROCHAMAR AGENCIA MARITIMA S/A. - STS"},
{num_contrato:"STR000667",	nome:"ROYAL CARIBBEAN CRUISES LIMITED"},
{num_contrato:"STR000746",	nome:"S. A. MARITIMA EUROBRAS AG.E COMISSARIA - STS"},
{num_contrato:"STR000571",	nome:"SAGA WELCO AS"},
{num_contrato:"STR000599",	nome:"SAVEIROS"},
{num_contrato:"STR000597",	nome:"SMIT REBRAS"},
{num_contrato:"STR000637",	nome:"STENA WECO A/S C/O PORTS DIRECT"},
{num_contrato:"STR000577",	nome:"STOLT TANKERS B.V - STS"},
{num_contrato:"STR000674",	nome:"SUISSE - ATLANTIQUE S.A."},
{num_contrato:"STR000614",	nome:"THORCO SHIPPING A/S C/O PORTS-DIRECT"},
{num_contrato:"STR000697",	nome:"TRANSGRAIN SHIPPING B.V."},
{num_contrato:"STR000698",	nome:"TRANSGRAIN SHIPPING PTE."},
{num_contrato:"STR000689",	nome:"UNITED BULK CARRIERS INTERNATIONAL"},
{num_contrato:"STR000600",	nome:"WALLENIUS WILHELMSEN"},
{num_contrato:"STR000673",	nome:"WILHELMSEN SHIPS"},
{num_contrato:"STR000427",	nome:"WORTHINGTON BULK LTD."},
{num_contrato:"STR000744",	nome:"YANG MING"},

{nome:"BBC"						,num_contrato:"RJ1000812"},
{nome:"CAMORIM"					,num_contrato:"RJ1000158"},
{nome:"ELCANO"					,num_contrato:"RJ1000839"},
{nome:"INTERMARINE"				,num_contrato:"RJ1000819"},
{nome:"ISS MARINE"				,num_contrato:"RJ1000859"},
{nome:"NAVIG8"					,num_contrato:"RJ1000532"},
{nome:"SAVEIROS"				,num_contrato:"RJ1000153"},
{nome:"STOLT"					,num_contrato:"RJ1000555"},
{nome:"THORCO A/C PORTS DIRECT"	,num_contrato:"RJ1000597"},
{nome:"WORTHINGTON"				,num_contrato:"RJ1000513"},
{nome:"WALLENIUS"				,num_contrato:"RJ1000590"},
{nome:"ALIANÇA",					num_contrato:"SEP000372"},
{nome:"BBC",						num_contrato:"SEP000368"},
{nome:"CAMORIM",					num_contrato:"SEP000309"},
{nome:"EDF A/C PORTS DIRECT",		num_contrato:"SEP000329"},
{nome:"GEARBULK",					num_contrato:"SEP000358"},
{nome:"HAMBURG SUD ( RAOBULK ) ",	num_contrato:"SEP000217"},
{nome:"NORDANA A/C PORTS DIRECT",	num_contrato:"SEP000365"},
{nome:"RBD A/C SSY",				num_contrato:"SEP000351"},
{nome:"SAAM SMIT",					num_contrato:"SEP000308"},
{nome:"SAVEIROS",					num_contrato:"SEP000388"},
{nome:"M2M PANAMAX",				num_contrato:"SEP000413"} 
];

